# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inerview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_person', models.CharField(blank=True, max_length=100)),
                ('interview_disciption', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_discription', models.CharField(max_length=2000)),
                ('project_img', models.ImageField(upload_to='images')),
                ('start_date_project', models.DateTimeField(null=True, verbose_name='date started')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_person', models.CharField(max_length=100)),
                ('story_title', models.CharField(max_length=200)),
                ('story_discription', models.CharField(max_length=2000)),
                ('story_img', models.ImageField(default=None, upload_to='images')),
                ('story_from_project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=200)),
                ('video_discription', models.CharField(blank=True, max_length=1000)),
                ('video_youtube_url', models.CharField(max_length=300, unique=True)),
                ('video_from_project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='inerview',
            name='interview_from_project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
