# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inerview',
            old_name='interview_disciption',
            new_name='interview_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_discription',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_discription',
            new_name='story_description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_discription',
            new_name='video_description',
        ),
    ]
