# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170928_1126'),
    ]

    operations = [
        migrations.RenameModel('inerview', 'interview')
    ]
