# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170928_1133'),
    ]

    operations = [
    ]
