# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170930_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default=None, upload_to='images/projects/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_img',
            field=models.ImageField(default=None, upload_to='images/stories/'),
        ),
    ]
