# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170930_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['date_started']},
        ),
        migrations.AddField(
            model_name='story',
            name='date_started',
            field=models.DateTimeField(default=None),
        ),
    ]
