# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20171110_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-date_started']},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_person',
            new_name='author',
        ),
    ]
