# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180128_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interview_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='interview_from_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='interview_person',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date_project',
            new_name='date_started',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_from_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_from_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_youtube_url',
            new_name='url',
        ),
    ]
