# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 10:02
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180201_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
