# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180202_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
