# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20180210_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-date_started']},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='date_created',
            new_name='date_started',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_created',
        ),
    ]
