# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 13:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20180708_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
