# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_team_team_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_short_description',
            new_name='short_description',
        ),
    ]
