# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 12:00
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_auto_20180128_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
