# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
