# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170930_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default=None, upload_to='images/members'),
        ),
    ]
